# -*- coding: utf-8 -*-
"""CI/CD Pipeline Monitor & Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1sEyvWd3UiDWmKNrdVAn4E3hqiXSSDK
"""

import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime, timedelta
import random
import json
from collections import defaultdict
import numpy as np

class CICDMonitor:
    def __init__(self):
        self.pipelines = {}
        self.build_history = defaultdict(list)
        self.deployment_history = []

    def add_pipeline(self, name, endpoint):
        """Add a pipeline to monitor"""
        self.pipelines[name] = {
            'endpoint': endpoint,
            'status': 'active',
            'builds': []
        }

    def simulate_pipeline_data(self, days=30):
        """Simulate pipeline data for demonstration"""
        pipeline_names = ['Frontend', 'Backend', 'API', 'Database']

        for pipeline in pipeline_names:
            self.add_pipeline(pipeline, f"http://{pipeline.lower()}.ci.com")

        # Generate historical data
        for day in range(days):
            date = datetime.now() - timedelta(days=days-day)

            for pipeline in pipeline_names:
                # 3-5 builds per day
                num_builds = random.randint(3, 5)

                for _ in range(num_builds):
                    build_time = date + timedelta(hours=random.randint(0, 23))
                    success = random.random() > 0.15  # 85% success rate
                    duration = random.randint(60, 600)  # 1-10 minutes

                    build_data = {
                        'timestamp': build_time,
                        'pipeline': pipeline,
                        'status': 'success' if success else 'failed',
                        'duration': duration,
                        'build_id': f"#{random.randint(1000, 9999)}"
                    }

                    self.build_history[pipeline].append(build_data)

                    if success and random.random() > 0.3:  # 70% of successful builds deploy
                        self.deployment_history.append({
                            'timestamp': build_time + timedelta(minutes=duration//60),
                            'pipeline': pipeline,
                            'environment': random.choice(['staging', 'production'])
                        })

    def calculate_success_rate(self, pipeline_name=None):
        """Calculate success rate for pipelines"""
        if pipeline_name:
            builds = self.build_history[pipeline_name]
        else:
            builds = [b for builds in self.build_history.values() for b in builds]

        if not builds:
            return 0

        successful = sum(1 for b in builds if b['status'] == 'success')
        return (successful / len(builds)) * 100

    def generate_dashboard(self):
        """Generate comprehensive CI/CD dashboard"""
        fig = plt.figure(figsize=(16, 12))
        fig.suptitle('CI/CD Pipeline Monitoring Dashboard', fontsize=20, fontweight='bold')

        # 1. Pipeline Success Rates
        ax1 = plt.subplot(2, 3, 1)
        pipelines = list(self.build_history.keys())
        success_rates = [self.calculate_success_rate(p) for p in pipelines]
        colors = ['#2ecc71' if sr >= 90 else '#f39c12' if sr >= 75 else '#e74c3c'
                  for sr in success_rates]

        bars = ax1.bar(pipelines, success_rates, color=colors, alpha=0.7, edgecolor='black')
        ax1.set_ylabel('Success Rate (%)', fontweight='bold')
        ax1.set_title('Pipeline Success Rates (Last 30 Days)', fontweight='bold')
        ax1.set_ylim(0, 100)
        ax1.axhline(y=90, color='green', linestyle='--', alpha=0.3, label='Target: 90%')
        ax1.legend()
        ax1.grid(axis='y', alpha=0.3)

        # Add value labels on bars
        for bar in bars:
            height = bar.get_height()
            ax1.text(bar.get_x() + bar.get_width()/2., height,
                    f'{height:.1f}%', ha='center', va='bottom', fontweight='bold')

        # 2. Build Duration Trends
        ax2 = plt.subplot(2, 3, 2)
        for pipeline in pipelines:
            builds = sorted(self.build_history[pipeline], key=lambda x: x['timestamp'])
            dates = [b['timestamp'] for b in builds[-20:]]  # Last 20 builds
            durations = [b['duration']/60 for b in builds[-20:]]  # Convert to minutes
            ax2.plot(dates, durations, marker='o', label=pipeline, linewidth=2, markersize=4)

        ax2.set_ylabel('Duration (minutes)', fontweight='bold')
        ax2.set_title('Build Duration Trends', fontweight='bold')
        ax2.legend(loc='best')
        ax2.grid(True, alpha=0.3)
        ax2.xaxis.set_major_formatter(mdates.DateFormatter('%m/%d'))
        plt.setp(ax2.xaxis.get_majorticklabels(), rotation=45)

        # 3. Daily Build Count
        ax3 = plt.subplot(2, 3, 3)
        all_builds = [b for builds in self.build_history.values() for b in builds]
        build_dates = [b['timestamp'].date() for b in all_builds]
        unique_dates = sorted(set(build_dates))
        daily_counts = [build_dates.count(d) for d in unique_dates]

        ax3.plot(unique_dates, daily_counts, marker='o', color='#3498db',
                linewidth=2, markersize=6)
        ax3.fill_between(unique_dates, daily_counts, alpha=0.3, color='#3498db')
        ax3.set_ylabel('Number of Builds', fontweight='bold')
        ax3.set_title('Daily Build Activity', fontweight='bold')
        ax3.grid(True, alpha=0.3)
        ax3.xaxis.set_major_formatter(mdates.DateFormatter('%m/%d'))
        plt.setp(ax3.xaxis.get_majorticklabels(), rotation=45)

        # 4. Success vs Failure Distribution
        ax4 = plt.subplot(2, 3, 4)
        success_counts = []
        failure_counts = []

        for pipeline in pipelines:
            builds = self.build_history[pipeline]
            success_counts.append(sum(1 for b in builds if b['status'] == 'success'))
            failure_counts.append(sum(1 for b in builds if b['status'] == 'failed'))

        x = np.arange(len(pipelines))
        width = 0.35

        bars1 = ax4.bar(x - width/2, success_counts, width, label='Success',
                       color='#2ecc71', alpha=0.8)
        bars2 = ax4.bar(x + width/2, failure_counts, width, label='Failed',
                       color='#e74c3c', alpha=0.8)

        ax4.set_ylabel('Build Count', fontweight='bold')
        ax4.set_title('Success vs Failure Distribution', fontweight='bold')
        ax4.set_xticks(x)
        ax4.set_xticklabels(pipelines)
        ax4.legend()
        ax4.grid(axis='y', alpha=0.3)

        # 5. Deployment Frequency
        ax5 = plt.subplot(2, 3, 5)
        deployment_dates = [d['timestamp'].date() for d in self.deployment_history]
        unique_deploy_dates = sorted(set(deployment_dates))
        daily_deploys = [deployment_dates.count(d) for d in unique_deploy_dates]

        ax5.bar(unique_deploy_dates, daily_deploys, color='#9b59b6', alpha=0.7,
               edgecolor='black')
        ax5.set_ylabel('Deployments', fontweight='bold')
        ax5.set_title('Daily Deployment Frequency', fontweight='bold')
        ax5.grid(axis='y', alpha=0.3)
        ax5.xaxis.set_major_formatter(mdates.DateFormatter('%m/%d'))
        plt.setp(ax5.xaxis.get_majorticklabels(), rotation=45)

        # 6. Pipeline Health Score
        ax6 = plt.subplot(2, 3, 6)
        health_scores = []

        for pipeline in pipelines:
            success_rate = self.calculate_success_rate(pipeline)
            builds = self.build_history[pipeline]
            avg_duration = np.mean([b['duration'] for b in builds])

            # Health score: 70% success rate, 30% speed (inverse of duration)
            speed_score = max(0, 100 - (avg_duration / 10))
            health_score = (success_rate * 0.7) + (speed_score * 0.3)
            health_scores.append(health_score)

        # Create radar chart
        angles = np.linspace(0, 2 * np.pi, len(pipelines), endpoint=False).tolist()
        health_scores_plot = health_scores + [health_scores[0]]
        angles += angles[:1]

        ax6 = plt.subplot(2, 3, 6, projection='polar')
        ax6.plot(angles, health_scores_plot, 'o-', linewidth=2, color='#e74c3c')
        ax6.fill(angles, health_scores_plot, alpha=0.25, color='#e74c3c')
        ax6.set_xticks(angles[:-1])
        ax6.set_xticklabels(pipelines)
        ax6.set_ylim(0, 100)
        ax6.set_title('Pipeline Health Scores', fontweight='bold', pad=20)
        ax6.grid(True)

        plt.tight_layout()
        plt.savefig('cicd_dashboard.png', dpi=300, bbox_inches='tight')
        print("✅ Dashboard saved as 'cicd_dashboard.png'")
        plt.show()

    def generate_report(self):
        """Generate text report"""
        print("\n" + "="*70)
        print(" "*20 + "CI/CD PIPELINE REPORT")
        print("="*70 + "\n")

        for pipeline in self.build_history.keys():
            builds = self.build_history[pipeline]
            success_rate = self.calculate_success_rate(pipeline)
            avg_duration = np.mean([b['duration'] for b in builds]) / 60
            total_builds = len(builds)

            print(f"📦 Pipeline: {pipeline}")
            print(f"   Total Builds: {total_builds}")
            print(f"   Success Rate: {success_rate:.2f}%")
            print(f"   Avg Duration: {avg_duration:.2f} minutes")
            print(f"   Status: {'✅ HEALTHY' if success_rate >= 85 else '⚠️  NEEDS ATTENTION'}")
            print()

        total_deployments = len(self.deployment_history)
        print(f"🚀 Total Deployments: {total_deployments}")
        print(f"📊 Overall Success Rate: {self.calculate_success_rate():.2f}%")
        print("\n" + "="*70 + "\n")

# Main execution
if __name__ == "__main__":
    print("🚀 Starting CI/CD Pipeline Monitor...")

    monitor = CICDMonitor()
    monitor.simulate_pipeline_data(days=30)

    print("📊 Generating dashboard...")
    monitor.generate_dashboard()

    monitor.generate_report()

    print("✅ Monitoring complete!")